[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.5.40", features = ["derive"] }
csv = "1.3.1"
dirs-next = "2.0.0"
serde = { version = "1.0.219", features = ["derive"] }
strum = "0.27.1"
strum_macros = "0.27.1"
